language: ruby
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
cache: bundler
rvm:
  - 2.1.5
  - 2.2.1
  - 2.3.0
  - jruby-19mode
branches:
  only:
    - master
install:
  - "travis_retry bundle install --jobs 8"
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
